### PR TITLE
Fix cache.open catch fallback

### LINKED ISSUE #234: When persistent cache fails to open, icons infinitely load
### Describe the bug

When [this call](https://github.com/gilbarbara/react-inlinesvg/blob/main/src/modules/cache.ts#L24-L25) to `caches.open` rejects, the icons that are subscribed stay in an infinitely loading state.

### Your minimal, reproducible example

Open in a non-secure context (`http`)

### Steps to reproduce

Make `caches.open` a function that rejects, and observer the behavior

### Expected behavior

The icons should still load

### How often does this bug happen?

Every time

### Screenshots or Videos

_No response_

### Platform

_No response_

### react-inlinesvg version

4.1.4

### TypeScript version

5.5.3

### Build tool

_No response_

### Additional context

going to put up a pr to fix this since it seems like a simple fix

### PR DESCRIPTION
**Pull request by peter-cardenas-ai**
fixes #234

### CODE REVIEW

File: src/modules/cache.ts [hunk 1]
```diff
@@ -31,6 +31,7 @@ export default class CacheStore {
         })
         .catch(error => {
           this.isReady = true;
+          this.subscribers.forEach(callback => callback());
```
Comment (gilbarbara) [inline src/modules/cache.ts:34]: Can you move the isReady assignment and the callback call to a `finally` block?

**Review by gilbarbara — CHANGES_REQUESTED** [review]
Other than the comment I left, LGTM.

**Review by gilbarbara — APPROVED** [review]
LGTM
