### PR TITLE
Fix handling of non-id hrefs

### LINKED ISSUE #125: UniquifyIDs breaks data-urls
When using `uniquifyIDs` any urls on `<image>`-elements will be broken as the unique-hash will be appended to the set URL. 

Since local ID references would start with `#` I propose a check is added to this line https://github.com/gilbarbara/react-inlinesvg/blob/master/src/index.tsx#L172 that tests if the value of the attribute starts with `#` if the attribute is a `href``

### PR DESCRIPTION
**Pull request by clentfort**
**Summary:**

Currently when uniquifying IDs every `href`-attribute, no matter if it
is a ID or not, will be uniqufied. This breaks URLs such as embedded
images.

Fixes #125

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -169,7 +170,7 @@ export default class InlineSVG extends React.PureComponent<IProps, IState> {
         replaceableAttributes.forEach(r => {
           const attribute = attributes.find(a => a.name === r);
 
-          if (attribute) {
+          if (attribute && !(linkAttributes.includes(r) && attribute.value[0] !== '#')) {
```
Comment (gilbarbara) [inline src/index.tsx]: I'm not including a polyfill for `includes` in the build, so it's better to use `indexOf`.
Also, I think it would be better to use `indexOf` in the `attribute.value` check too.

File: test/index.spec.tsx [hunk 2]
```diff
@@ -209,6 +210,27 @@ describe('react-inlinesvg', () => {
       );
     });
 
+    it('should not uniquify non-id hrefs', async () => {
+      const original = await setup({
```
Comment (gilbarbara) [inline test/index.spec.tsx]: I don't think is necessary to create an `original` instance to compare data.
Just check if the wrapped component with `uniquifyIDs` set to `true` doesn't change the prop.

Comment (clentfort) [reply test/index.spec.tsx]: How would I do that? With a snapshot?

**Comment by clentfort** [comment]
Thanks for merging this so fast!
